### ISSUE TITLE
migrate library to IBPSA

### ISSUE THREAD

**Issue by mwetter** [ibpsa/modelica#674]
This branch is to migrate the Annex60 library to an IBPSA repository.

**Comment by mwetter** [comment]
@Mathadon 
Can you please check why 
```python
python bin/convertAnnex60ToIBPSA.py
```
wrongly removes the `https`. See
```bash
git diff Annex60/Airflow/Multizone/BaseClasses/powerLawFixedM.mo
...
-for <a href=\"https://github.com/iea-annex60/modelica-annex60/issues/404\">#404</a>.
+for <a href=\"github.com/ibpsa/modelica/issues/404\">#404</a>.
...
```

**Comment by mwetter** [comment]
@Mathadon At least I read your github comments :)

**Comment by mwetter** [comment]
To update your working branch, you may need to set the git rename limit setting to a higher value. For example, use
```
git checkout "your_branch"
git config merge.renameLimit 1899
git merge master
```

**Comment by thorade** [comment]
Updating the remote URL is also easy, github has a help article on it:
https://help.github.com/articles/changing-a-remote-s-url/

**Comment by thorade** [comment]
The new repository name is  `modelica`, just like the Modelica Standrad Library:
https://github.com/ibpsa/modelica
https://github.com/modelica/modelica
That has one consequence: I you fork both repositories to your personal account, they cannot have the same name and one of the two will be renamed to `modelica-1`.
Not really a problem, just a minor flaw.

**Comment by marcusfuchs** [comment]
Related to this, I wonder whether we can agree on one definitive name of the library to be always used consistently.

In the `README`, the library is called 

> Modelica *IBPSA* library

With "library" starting with a small "l", and "Modelica" possibly not being part of the name in a strict sense, as "*IBPSA*" is set in italics and "Modelica" is not, some people may think the library is called "*IBPSA*". In contrast, something like "IBPSA Modelica Library" would in my opinion make it clear that all 3 words are part of the library name. Of course, I am also open to any other name, I just think it would be beneficial to agree on one name and always only use that name.

**Comment by thorade** [comment]
According to the package.mo `within ;` statement, the libraries name is `IBPSA`.
Would you prefer to call it IBPSLib (International Building Performance Simulation Library)? ;-)

**Comment by mwetter** [comment]
@marcusfuchs I will capitalize the 'L' in "Modelica IBPSA Library".

@thorade : We should keep the top-level name IBPSA as this is the organization name, has been approved by the IBPSA board and used in various documentations already.

**Comment by tsnouidui** [comment]
@mwetter @marcusfuchs @thorade 
Minor note: I don't understand why the L should be capitalized in library. I think that Modelica _IBPSA_ library is OK.
We also do not write Buildings Library or IDEAS Library I think? 
IMO it is sufficient to highlight the name of the library by writing it in italics or any other way and leaving the l in library small case.

**Comment by marcusfuchs** [comment]
My suggestion with a capitalized "L" was motivated by trying to give it a unique clear name. @tsnouidui you are right, we do not write "Buildings Library" or "IDEAS Library". I would think that this is not necessary, as "Buildings" and "IDEAS" are the unique names to use, and in some contexts it may be useful to speak of the "Buildings library", in others "Buildings" is enough. In contrast, the "Modelica Standard Library" has a capitalized L. I would think that is because neither "Modelica" nor "Modelica Standard" are names that would uniquely and unabiguously work for the library. I argue that we have the same case with "IBPSA" being the name of the association, so it would not be a unique name for the library. Therefore, one solution would be the "Modelica IBPSA Library" or something similar.

**Comment by mwetter** [comment]
I used the capitalization with the same reasoning as @marcusfuchs

**Comment by tsnouidui** [comment]
I think the naming convention is in a sense fuzzy. I would have expected the highlighted name of the library to be the same as the top level package name. The Standard Library is in a sense also fuzzy since the package name is Modelica and the name of the library itself is "Modelica Standard Library".

**Comment by marcusfuchs** [comment]
@tsnouidui I completely agree.
