### ISSUE TITLE
Documentation ReducedOrder: Add reference to TEASER

### ISSUE THREAD

**Issue by PRemmen** [ibpsa/modelica#700]
Since TEASER is an open-source project with a stable version and can be used to calculate all parameters and generate code for all four reduced order models contained in IBPSA library, I suggest to add a reference of TEASER to the documentation of `ReducedOrder` package description.

Repository: https://github.com/RWTH-EBC/TEASER

Documentation: http://rwth-ebc.github.io/TEASER/

Any objections? :)

**Comment by mwetter** [comment]
@PRemmen Adding such a reference would be good. Can you please make a pull request against the branch `issue700_romDocumentation`.

Also, on http://rwth-ebc.github.io/TEASER/ I suggest you list the four libraries as we want end-users to use any of the four libraries directly rather than the IBPSA library.
The section is:

> export of individual dynamic simulation models for Modelica libraries AixLib and Modelica IBPSA library.
